site_name: Zscode
site_description: The web site of Zscode
site_author: Z
site_url: https://Zect3279.github.io

theme:
    name: material
    custom_dir: overrides
    palette:
        scheme: preference
        primary: indigo
        accent: amber
    font:
        text: Noto Sans
    language: ja
    # logo: img/
    # favicon: img/
    icon:
        repo: fontawesome/brands/github
    # features:
        # - navigation.indexes

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.tabbed
    - footnotes
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
        generic: true
    - meta
